function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	AddTextEntry("NULL_SPOILER", "Aero Package")
	AddTextEntry("NULL_WINGLESS", "Aero Package & Wingless")
	AddTextEntry("F10M5_WINGRICE", "Awful Forza Spoiler")
	AddTextEntry("F10M5_SPLITRICE", "Awful Forza Splitter")
	AddTextEntry("F10M5_FCAGE", "Forza Rollcage")
	AddTextEntry("BMW", "BMW")
	AddTextEntry("F10M5", "M5 F10")
	AddTextEntry("F10M5_NFS_EXH_01", "Speedhunters Style 1")
	AddTextEntry("F10M5_NFS_EXH_02", "Speedhunters Style 2")
	AddTextEntry("F10M5_NFS_EXH_02A", "Speedhunters Style 2.5")
	AddTextEntry("F10M5_NFS_EXH_03", "Speedhunters Style 3")
	AddTextEntry("F10M5_NFS_EXH_03A", "Speedhunters Style 3.5")
	AddTextEntry("F10M5_NFS_EXH_04", "Speedhunters Style 4")
	AddTextEntry("F10M5_NFS_EXH_04A", "Speedhunters Style 4.5")
	AddTextEntry("F10M5_NFS_EXH_05", "Speedhunters Style 5")
	AddTextEntry("F10M5_NFS_EXH_06", "Speedhunters Style 6")
	AddTextEntry("F10M5_NFS_EXH_07", "Speedhunters Style 7")
	AddTextEntry("F10M5_NFS_EXH_08", "Speedhunters Style 8")
	AddTextEntry("F10M5_NFS_EXH_09", "Speedhunters Style 9")
	AddTextEntry("F10_M5_BUMR1", "Carbon Rear Bumper")
	AddTextEntry("F10_M5_BUMR1A", "Carbon Rear Bumper W/ Diffuser")
	AddTextEntry("F10_M5_PLUSH_MIRROR", "GVMA Mirror Mascot")
	AddTextEntry("F10_M5_PLUSH_CHASSIS", "GVMA Boot Mascot")
	AddTextEntry("VMT_M5_MASCOT", "Mascots")
	AddTextEntry("F10_M5_PLUSH_ALL", "All The Mascots")
	AddTextEntry("M5_RBSWAP", "Standard Twin Turbo RB26")
	AddTextEntry("M5_RBSWAP_STURBO", "Upgraded Single Turbo RB26")
	AddTextEntry("M5_GRILLE_FULLBLCK", "Black Grille")
	AddTextEntry("M5_GRILLE_FULLBLCK_A", "Black M-Sport Grille")
	AddTextEntry("M5_GRILLE_FULLCHRM", "Chrome Grille")
	AddTextEntry("M5_GRILLE_FULLCHRM_A", "Chrome M-Sport Grille")
	AddTextEntry("M5_GRILLE_CARB", "Carbon Grille")
	AddTextEntry("M5_GRILLE_CARB_A", "Carbon M-Sport Grille")
	AddTextEntry("M5_GRILLE_B_HALFCHRM", "Alt Stock Grille")
	AddTextEntry("M5_GRILLE_B_HALFCHRM_A", "Alt Stock M-Sport Grille")
	AddTextEntry("M5_GRILLE_B_FULLCHRM", "Alt Chrome Grille")
	AddTextEntry("M5_GRILLE_B_FULLCHRM_A", "Alt Chrome M-Sport Grille")
	AddTextEntry("M5_GRILLE_B_FULLBLCK", "Alt Black Grille")
	AddTextEntry("M5_GRILLE_B_FULLBLCK_A", "Alt Black M-Sport Grille")
	AddTextEntry("M5_GRILLE_B_CARB", "Alt Carbon Grille")
	AddTextEntry("M5_GRILLE_B_CARB_A", "Alt Carbon M-Sport Grille")
	AddTextEntry("F10_M5_BUMPER_F1", "Modern Bumper")
	AddTextEntry("F10_M5_BUMPER_F1_ACC", "Modern Bumper W/ Foglights")
	AddTextEntry("F10_M5_BUMPER_F1_ACCA", "Modern Bumper W/ Awful Splitter & Foglights")
	AddTextEntry("F10_M5_BUMPER_F1_ACCB", "Modern Bumper W/ Custom Splitter & Foglights")
	AddTextEntry("F10_M5_BUMPER_F1_ACC2", "Modern Bumper W/ Tinted Foglights")
	AddTextEntry("F10_M5_BUMPER_F1_ACC2A", "Modern Bumper W/ Awful Splitter & Tinted Foglights")
	AddTextEntry("F10_M5_BUMPER_F1_ACC2B", "Modern Bumper W/ Custom Splitter & Tinted Foglights")
	AddTextEntry("F10_M5_HKS_01", "HKS Hi-Power Muffler")
	AddTextEntry("M5_F10_SPLIT_F_01", "Custom Splitter")
	AddTextEntry("M5_F10_SPLIT_F_01B", "Modern Bumper W/ Custom Splitter")
	AddTextEntry("M5_F10_SPLIT_F_01A", "Modern Bumper W/ Awful Splitter")
	AddTextEntry("F10M5_CUSTOMWING_01", "Carbon Stock Spoiler")
	AddTextEntry("F10M5_REMWING", "Remove Spoiler")
	AddTextEntry("M5_F10_SPOILERSTEW", "Custom Spoiler")
	AddTextEntry("M5_F10_SPOILERSTEW_A", "Custom Carbon Spoiler")
	AddTextEntry("F10M5_BUMFACC_01", "Stock Bumper W/ OEM Foglights")
	AddTextEntry("F10M5_BUMFACC_01A", "Stock W/ Awful Splitter & OEM Foglights")
	AddTextEntry("F10M5_BUMFACC_01B", "Stock W/ Custom Splitter & OEM Foglights")
	AddTextEntry("M5_GRILLE_FULLCHRM_C", "Chrome Diamond Grille")
	AddTextEntry("M5_GRILLE_FULLBLCK_C", "Black Diamond Grille")
	AddTextEntry("M5_GRILLE_CARB_C", "Carbon Diamond Grille")
	AddTextEntry("F10_M5_BONNET_CARBON", "Carbon Bonnet")
	AddTextEntry("F10_M5_BON_CUSTOM", "Vented Bonnet")
	AddTextEntry("F10_M5_BON_CUSTOM_B", "Carbon Vented Bonnet")
	AddTextEntry("F10_M5_BON_CUSTOM2", "Custom Vented Bonnet")
	AddTextEntry("F10_M5_BON_CUSTOM2_C", "Carbon Custom Vented Bonnet")
	AddTextEntry("F10_M5_BON_CUSTOM3", "Power Bulge")
	AddTextEntry("F10_M5_BON_CUSTOM3_C", "Carbon Power Bulge")
	AddTextEntry("F10_M5_BON_CUSTOM4", "Power Bulge W/ Vents")
	AddTextEntry("F10_M5_BON_CUSTOM4_C", "Carbon Power Bulge W/ Vents")
	AddTextEntry("F10_M5_WIDE_01", "Custom PD54X Widebody Kit")
	AddTextEntry("F10_M5_ARIEL_01", "Carbon Antenna")
	AddTextEntry("F10_M5_ARIEL_02", "Blanking Plate (Remove Antenna)")
	AddTextEntry("M5_F10_ENG_V10", "Standard E60 M5 V10")
	AddTextEntry("F10M5RC", "RC F10 M5")
	AddTextEntry("F10_M5_LIVERY_1", "BMW M Motorsport")
	--GTR C
	AddTextEntry('0xFF1F5E98','Downforce COPIUM')
	--Boxville
	AddTextEntry('0xC33D77CC','NoPixel Cards')
	AddTextEntry('0x81097365','Dodo Logistics')
	AddTextEntry('0x726DD62E','Dodo Prime')
	AddTextEntry('0xA4CA3AEA','Vultur Le Culture')
	--Deluxo
	AddTextEntry('0x850EC7A8','Back to the Future by Viper')
	AddTextEntry('0x6FBE9D08','Black Waves by Kikobri')
	AddTextEntry('0x7994B0B4','Brutal by Brutal')
	AddTextEntry('0x4C11D5AF','Brutal Black by Brutal')
	AddTextEntry('0x563AEA01','Glitch Dark by Clear')
	AddTextEntry('0x0D9A5A69','Glitch Light by Clear')
	AddTextEntry('0x1B287585','Horimono by Hammling')
	AddTextEntry('0x28E91106','Initial D by Viper')
	AddTextEntry('0x46D84CE4','Irezumi by Hammling')
	AddTextEntry('0xCB8FD9BD','6STR by Viper')
	AddTextEntry('0xD01AE2D3','Rooster Black by Clear')
	AddTextEntry('0xA6538F45','Rooster Yellow by Clear')
	AddTextEntry('0xB4A52BE8','Timelord 2077 Blue by SpartanOne')
	AddTextEntry('0x0A71D780','Timelord 2077 Red by SpartanOne')
	AddTextEntry('0x16C0701D','Timelord 2077 White by SpartanOne')
	AddTextEntry('0xED0F1CBB','Vix by Vix')
	AddTextEntry('0xFB94B9C6','White Waves by Kikobri')
	--Mustang
	AddTextEntry('0x1AC92852','RTR Spec2')
	AddTextEntry('0x2C2380BA','Spoiler2')
	AddTextEntry('0x4C1A2A85','Works Motorsport')
	AddTextEntry('0x6FD3F1F8','Eleanor')
	AddTextEntry('0x7DF2EA80','Raijin2')
	AddTextEntry('0x9D8FADDD','Shelby GT350R')
	AddTextEntry('0x1DE74E20','Shelby GT350R')
	AddTextEntry('0x30C1A8A7','Works Motorsport')
	AddTextEntry('0x41F1AC56','Spoiler1')
	AddTextEntry('0x60FA0F67','Mustang Cage')
	AddTextEntry('0x70AF09D0','Shelby GT350R')
	AddTextEntry('0x70B14FFD','Shelby GT350R')
	AddTextEntry('0x85ACF9F0','Works Motorsport')
	AddTextEntry('0x86E73640','RTR Spec5')
	AddTextEntry('0x95BA78B3','RTR Spec2')
	AddTextEntry('0x418E156D','Apollo Edition')
	AddTextEntry('0x683C9DB8','RTR Spec5')
	AddTextEntry('0x776B5D6D','Raijin')
	AddTextEntry('0x8733A0BF','RTR Spec5')
	AddTextEntry('0x9531D2D5','Spoiler3')
	AddTextEntry('0x27905D86','Works Motorsport')
	AddTextEntry('0x303598BD','Eleanor')
	AddTextEntry('0x1397746B','Shelby GT350R')
	AddTextEntry('0x78650322','RTR Spec2')
	AddTextEntry('0xB6C81C42','Ford Mustang GT')
	AddTextEntry('0xB111D0B9','RTR Spec5')
	AddTextEntry('0xB7059BE1','Shelby GT350R')
	AddTextEntry('0xD2F44E49','Mustang GT')
	AddTextEntry('0xE1FA6C65','RTR Spec2')
	--C7
	AddTextEntry('0x4A1931C5','Z06')
	AddTextEntry('0x56DF3703','Z06')
	AddTextEntry('0x342378AB','Chevrolet Corvette Stingray(C7) 14')
	AddTextEntry('0x35966909','Roof')
	AddTextEntry('0xB3A4AA28','Hennessy')
	AddTextEntry('0xC2D17AE5','Z06')
	AddTextEntry('0xC440B206','C7R Edition')
	AddTextEntry('0xCC7F463E','Hennessy')
	AddTextEntry('0xCE8648AE','Hennessy')
	AddTextEntry('0xD94B5B62','Z06')
	AddTextEntry('0xF5ACE7AB','Z06')
	--Challenger
	AddTextEntry('0x23B6AF16','SRT Spoiler')
	--News
	AddTextEntry('0xE3613EAD','LSBN News')
	AddTextEntry('0xD11A9A20','LSBN News Inverse')
	AddTextEntry('0x413AFA63','Weazel News')
	--Everything Else
end)
